import type { NextConfig } from "next";


const nextConfig: NextConfig = {

  serverExternalPackages: [
    "iyzipay"
  ],


  outputFileTracingIncludes: {

    "/api/payment/create": [
      "./node_modules/stream-length/**",
      "./node_modules/asynckit/**",
      "./node_modules/@postman/form-data/**",
      "./node_modules/extsprintf/**",
"./node_modules/verror/**",
"./node_modules/core-util-is/**",
"./node_modules/uuid/**",
"./node_modules/buffer-equal/**",
"./node_modules/json-schema-traverse/**",
"./node_modules/har-validator/**",
"./node_modules/tough-cookie/**",
"./node_modules/caseless/**",
"./node_modules/combined-stream/**",
"./node_modules/delayed-stream/**",
"./node_modules/forever-agent/**",
"./node_modules/isstream/**",
"./node_modules/is-typedarray/**",
"./node_modules/performance-now/**",
"./node_modules/json-stringify-safe/**",
      "./node_modules/jsprim/**",
"./node_modules/asn1/**",
"./node_modules/json-schema/**",
"./node_modules/jsbn/**",
"./node_modules/bcrypt-pbkdf/**",
"./node_modules/tweetnacl/**",
      "./node_modules/safer-buffer/**",
"./node_modules/asn1/**",
"./node_modules/bcrypt-pbkdf/**",
"./node_modules/dashdash/**",
"./node_modules/ecc-jsbn/**",
"./node_modules/jsbn/**",
"./node_modules/tweetnacl/**",
"./node_modules/core-util-is/**",
"./node_modules/is-typedarray/**",
"./node_modules/isstream/**",
"./node_modules/oauth-sign/**",
"./node_modules/hawk/**",
"./node_modules/boom/**",
"./node_modules/hoek/**",
"./node_modules/cryptiles/**",
"./node_modules/sntp/**",
      "./node_modules/iyzipay/**",
      "./node_modules/postman-request/**",
      "./node_modules/extend/**",
      "./node_modules/@postman/tough-cookie/**",
      "./node_modules/punycode/**",
      "./node_modules/url-parse/**",
      "./node_modules/requires-port/**",
      "./node_modules/querystringify/**",
      "./node_modules/psl/**",
      "./node_modules/universalify/**",
      "./node_modules/aws-sign2/**",
      "./node_modules/aws4/**",
      "./node_modules/oauth-sign/**",
      "./node_modules/http-signature/**",
      "./node_modules/har-validator/**",
      "./node_modules/sshpk/**",
      "./node_modules/assert-plus/**",
      "./node_modules/caseless/**",
      "./node_modules/forever-agent/**",
      "./node_modules/form-data/**",
      "./node_modules/json-stringify-safe/**",
      "./node_modules/tough-cookie/**",
      "./node_modules/mime-types/**",
      "./node_modules/combined-stream/**",
      "./node_modules/delayed-stream/**",
      "./node_modules/is-typedarray/**",
      "./node_modules/isstream/**",
      "./node_modules/performance-now/**",
      "./node_modules/json-schema-traverse/**"
      
    ],


    "/api/payment/callback": [
      "./node_modules/stream-length/**",
      "./node_modules/asynckit/**",
      "./node_modules/@postman/form-data/**",
      "./node_modules/extsprintf/**",
"./node_modules/verror/**",
"./node_modules/core-util-is/**",
"./node_modules/uuid/**",
"./node_modules/buffer-equal/**",
"./node_modules/json-schema-traverse/**",
"./node_modules/har-validator/**",
"./node_modules/tough-cookie/**",
"./node_modules/caseless/**",
"./node_modules/combined-stream/**",
"./node_modules/delayed-stream/**",
"./node_modules/forever-agent/**",
"./node_modules/isstream/**",
"./node_modules/is-typedarray/**",
"./node_modules/performance-now/**",
"./node_modules/json-stringify-safe/**",
      "./node_modules/jsprim/**",
"./node_modules/asn1/**",
"./node_modules/json-schema/**",
"./node_modules/jsbn/**",
"./node_modules/bcrypt-pbkdf/**",
"./node_modules/tweetnacl/**",
      "./node_modules/safer-buffer/**",
"./node_modules/asn1/**",
"./node_modules/bcrypt-pbkdf/**",
"./node_modules/dashdash/**",
"./node_modules/ecc-jsbn/**",
"./node_modules/jsbn/**",
"./node_modules/tweetnacl/**",
"./node_modules/core-util-is/**",
"./node_modules/is-typedarray/**",
"./node_modules/isstream/**",
"./node_modules/oauth-sign/**",
"./node_modules/hawk/**",
"./node_modules/boom/**",
"./node_modules/hoek/**",
"./node_modules/cryptiles/**",
"./node_modules/sntp/**",
      "./node_modules/iyzipay/**",
      "./node_modules/postman-request/**",
      "./node_modules/extend/**",
      "./node_modules/@postman/tough-cookie/**",
      "./node_modules/punycode/**",
      "./node_modules/url-parse/**",
      "./node_modules/requires-port/**",
      "./node_modules/querystringify/**",
      "./node_modules/psl/**",
      "./node_modules/universalify/**",
      "./node_modules/aws-sign2/**",
      "./node_modules/aws4/**",
      "./node_modules/oauth-sign/**",
      "./node_modules/http-signature/**",
      "./node_modules/har-validator/**",
      "./node_modules/sshpk/**",
      "./node_modules/assert-plus/**",
      "./node_modules/caseless/**",
      "./node_modules/forever-agent/**",
      "./node_modules/form-data/**",
      "./node_modules/json-stringify-safe/**",
      "./node_modules/tough-cookie/**",
      "./node_modules/mime-types/**",
      "./node_modules/combined-stream/**",
      "./node_modules/delayed-stream/**",
      "./node_modules/is-typedarray/**",
      "./node_modules/isstream/**",
      "./node_modules/performance-now/**",
      "./node_modules/json-schema-traverse/**"
    ]

  }

};


export default nextConfig;